samplesheet:
    samplesheet.tsv

workdir:
    /home/yuk5/yuk5/project/1.FPDMM/05.SingleCell/2205

references:
    genome_fa:   https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Human_hg38_Gencode_v39/human_GRCh38_no_alt_analysis_set.fasta
    anno_gtf:  https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Human_hg38_Gencode_v39/gencode.v39.annotation.sorted.gtf
    polya:       https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Human_hg38_Gencode_v39/polyA.list.txt
    tssbed:      https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Human_hg38_Gencode_v39/refTSS_v3.3_human_coordinate.hg38.sorted.bed
    barcode:     https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-10x_barcodes/3M-february-2018-REVERSE-COMPLEMENTED.txt.gz
    primer3:     https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-10x_primers/10x_3kit_primers.fasta
    mas16:       https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-MAS_adapters/MAS-Seq_Adapter_v1/mas16_primers.fasta
modules:
    smrtanalysis: smrtanalysis/11.1.0.166339
    sambamba: sambamba/0.8.2

max-jobs-per-second: 1
latency-wait: 120
keep-going: true
